{{- if .Values.googleCredentials.workloadIdentity.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guhatek-onegt.fullname" . }}-google-wif-config
  labels:
    {{- include "guhatek-onegt.labels" . | nindent 4 }}
data:
  {{ .Values.googleCredentials.filename | default "google-credentials-config.json" }}: |
    {
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/{{ .Values.googleCredentials.workloadIdentity.gcpProjectNumber }}/locations/global/workloadIdentityPools/{{ .Values.googleCredentials.workloadIdentity.poolId }}/providers/{{ .Values.googleCredentials.workloadIdentity.providerId }}",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "{{ .Values.googleCredentials.workloadIdentity.azureTokenPath }}"
      },
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/{{ .Values.googleCredentials.workloadIdentity.serviceAccountEmail }}:generateAccessToken"
    }
{{- end }}
